name: Function Deployment

on: workflow_dispatch

env:
  PYTHON_VERSION: "3.8"
  FUNCTION_APP: "dgeventdrivenfnceus2"
  FUNCTION_APP_PATH: "./functions"
  AZURE_SP_CREDENTIALS: ${{ secrets.AZURE_SP_CREDENTIALS }}

jobs:
  build-and-deploy:
    name: Build and Deploy Azure Function
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_SP_CREDENTIALS }}
      
      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Dependencies
        run: |
          pushd "${{ env.FUNCTION_APP_PATH }}"
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt --target=".python_packages/lib/site-packages"; fi
          popd
      
      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP }}
          package: ${{ env.FUNCTION_APP_PATH }}
